#!/usr/bin/env python3
"""gen_tables.py — the rows of the paper's generated tables, as LaTeX.

  make numbers       (runs it with the analysis environment, after gen_numbers.py)

A table with many cells is written here, row by row, from lab/reports/data, so no cell is
ever typed; the section files hold only each table's frame (columns, headings, caption).
Every table is checked against numbers the text already quotes, and the script stops if
they disagree. Writes paper/generated/tab-*.tex. Two more sets of rows are built only to
be checked against the text that quotes them (what a rollout costs, what rollouts read
through git) and are not written.
"""
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

CORTEX = Path(__file__).resolve().parents[3]
PAPER = CORTEX / "paper"                      # the paper's sources, kept outside the repository
sys.path.insert(0, str(CORTEX / "lab" / "reports" / "analysis"))
import load                                   # noqa: E402
import rebuild as RB                          # noqa: E402
import rescore                                # noqa: E402
import stats as S                             # noqa: E402

DATA = CORTEX / "lab" / "reports" / "data"
OUT = PAPER / "generated"


def rows(name):
    return [json.loads(l) for l in (DATA / name).read_text().splitlines() if l.strip()]


def macros():
    import re
    t = (OUT / "numbers.tex").read_text()
    return dict(re.findall(r"\\newcommand\{\\(\w+)\}\{(.*)\}", t))


def stop(why):
    raise SystemExit(f"gen_tables.py: {why}")


def pct(x):                                   # a share as a whole percentage, rounded half up
    return str(int(100 * x + 0.5 + 1e-9))


def num(x):                                   # thousands with a thin LaTeX group separator
    return f"{x:,}".replace(",", "{,}")


def tt(s):                                    # a file name or glob, set as a command
    return r"\cmd{" + s.replace("_", r"\_") + "}"


def write(name, body):
    (OUT / name).write_text("% generated by lab/reports/analysis/gen_tables.py — do not edit\n" + body)
    print(f"-> {OUT / name}")


def main():
    d = load.Data()
    ev = d.evaluation
    M = macros()
    runs = {r["run"]: r for r in rows("runs.jsonl")}

    # ---- the held-out gain by family: evolved against none, complete-case (as H1) --------
    def signed(v):                            # points, one decimal, with a real minus sign
        t = f"{v * 100:+.1f}"
        if t in ("+0.0", "-0.0"):             # zero carries no sign, as in the text and figures
            return "0.0"
        return t.replace("-", r"\textminus{}", 1) if t.startswith("-") else t

    def pval(v):
        return f"{v:.4f}" if v < 0.001 else f"{v:.3f}"
    keep = set(d.complete_case_tasks(ev, arms=("none", "evolved"), split="holdout"))
    hrows = [r for r in d.bench(runs=ev, arms=("none", "evolved"), split="holdout")
             if r["task"] in keep]
    rule = ["A", "B", "C", "E"]
    name = {"A": "A, changelog", "B": "B, money", "C": "C, exporters", "E": "E, time",
            "D": "D, plain bugs (control)", None: "A, B, C, E together"}
    cells = {}
    for f in rule + [None, "D"]:
        fams = [f] if f else rule
        cs = S.cells(hrows, "none", "evolved", families=fams, split="holdout")
        sel = [r for r in hrows if r.get("family") in fams]
        k0, n0, p0 = S.rate(sel, split="holdout", arm="none")
        k1, n1, p1 = S.rate(sel, split="holdout", arm="evolved")
        lo, hi, _ = S.two_way_bootstrap(cs)
        _, p, pairs = S.permutation_p(hrows, "none", "evolved", families=fams, split="holdout")
        cells[f] = dict(scen=len({t for _r, t in cs}), pairs=pairs, roll=n0 + n1, none=p0,
                        evolved=p1, gain=S.paired_mean(cs), lo=lo, hi=hi, p=p)
    holm = dict(zip(rule, S.holm([cells[f]["p"] for f in rule])))
    # every cell the text also quotes must be the same number
    quoted = [(None, "Hone"), ("A", "FamA"), ("B", "FamB"), ("C", "FamC"), ("E", "FamE"), ("D", "Htwo")]
    for f, mac in quoted:
        c = cells[f]
        if (signed(c["gain"]), signed(c["lo"]), signed(c["hi"])) != (M[f"{mac}Est"], M[f"{mac}Lo"], M[f"{mac}Hi"]):
            stop(f"the held-out table's row {name[f]!r} disagrees with the text")
    if (str(cells[None]["scen"]), str(cells[None]["pairs"])) != (M["CompleteTasks"], M["HoneTasks"]):
        stop("the held-out table's scenarios disagree with the text")
    if "= " + pval(cells[None]["p"]) != M["HoneP"] or any("= " + pval(holm[f]) != M["FamHolmP"] for f in rule):
        stop("the held-out table's p-values disagree with the text")
    body = []
    for f in rule + [None, "D"]:
        c = cells[f]
        if f is None or f == "D":
            body.append(r"\midrule")
        lab = rf"\textbf{{{name[f]}}}" if f is None else name[f]
        body.append(rf"{lab} & {c['scen']} & {num(c['roll'])} & {pct(c['none'])}\% & "
                    rf"{pct(c['evolved'])}\% & {signed(c['gain'])} & "
                    rf"[{signed(c['lo'])}, {signed(c['hi'])}] & {pval(c['p'])} & "
                    rf"{pval(holm[f]) if f in holm else ''} \\")
    write("tab-main.tex", "\n".join(body) + "\n")

    # ---- what a held-out rollout costs, by harness, in the runs that measured it ---------
    # (§5.4 quotes these in a paragraph; the rows are built to check what it says)
    def cost(run_list, arm):
        rs = [r for r in d.bench(runs=run_list, arms=(arm,), split="holdout") if r.get("valid", 1)]
        n = len(rs)
        mean = lambda k: sum(r.get(k) or 0 for r in rs) / n
        chars = d.arm_meta(run_list, arm, "always_on_chars")
        return n, chars, mean("tokens"), mean("cost_usd"), mean("turns"), mean("tool_calls"), mean("secs")
    blocks = [("R1--R4", ev, ("none", "evolved")),
              ("R1", ["R1"], ("none", "evolved", "none2", "kitchen", "ideal", "flat", "desc-only")),
              ("R2", ["R2"], ("none", "evolved", "accept-all"))]
    # the text quotes the four-run primary costs: they must be these; and every arm with
    # advice in context cost more per rollout than no harness, in the run that measured it
    a, b = cost(ev, "none")[3], cost(ev, "evolved")[3]
    base = {label: cost(run_list, "none")[3] for label, run_list, arms in blocks}
    later = cost(["R1"], "none2")[3]            # no harness, in the ablations' own batch
    for label, run_list, arms in blocks:
        for arm in arms:
            if arm not in ("none", "none2") and not cost(run_list, arm)[3] > max(base[label], later):
                stop(f"{arm} ({label}) does not cost more per rollout than no harness")
    if f"{a:.3f}" != M["CostNone"] or f"{b:.3f}" != M["CostEvolved"]:
        stop("the primary arms' cost per rollout disagrees with the text")

    # ---- what running the loop cost, per evaluation run ---------------------------------
    sess = defaultdict(float)
    for s in rows("sessions.jsonl"):
        sess[s["run"]] += s.get("cost_usd") or 0
    # the agent's own cost is the sessions plus /evolve's turns: with the loop off (control),
    # the two are the same, which is what lets them be told apart
    for c in d.control:
        if abs(runs[c]["agent_cost_usd"] - sess[c]) > 0.01:
            stop("the control run's agent cost is not its sessions' cost")
    cyc = [c for c in rows("cycles.jsonl") if c.get("is_cycle")]
    cs = rescore.candidates()
    sw = rows("sweeps.jsonl")
    tot, per_run = defaultdict(float), {}
    for run in ev:
        evolve = runs[run]["agent_cost_usd"] - sess[run]
        sweeps = [s for s in sw if s["run"] == run]
        vals = {"cycles": sum(1 for c in cyc if c["run"] == run),
                "swept": sum(1 for c in cs if c["run"] == run),
                "kept": sum(1 for c in cs if c["run"] == run and c["verdict"] == "KEEP"),
                "sessions": sess[run], "evolve": evolve,
                "rollouts": sum(s.get("rollouts") or 0 for s in sweeps),
                "sweep_usd": sum(s.get("cost_usd") or 0 for s in sweeps)}
        per_run[run] = vals
        for k, v in vals.items():
            tot[k] += v
    if (str(int(tot["cycles"])), str(int(tot["swept"])), str(int(tot["kept"]))) != (
            M["LoopCycles"], M["LoopSwept"], M["KeptItems"]) or num(int(tot["rollouts"])) != M["LoopRollouts"]:
        stop("the loop's costs do not add up to the funnel's counts")
    # the ranges §5.4 quotes: what the sweeps, /evolve's own turns and the sessions cost a run
    for key, mac in (("sweep_usd", "SweepCost"), ("evolve", "EvolveCost"), ("sessions", "SessionCost")):
        got = (f"{min(v[key] for v in per_run.values()):.2f}", f"{max(v[key] for v in per_run.values()):.2f}")
        if got != (M[mac + "Lo"], M[mac + "Hi"]):
            stop(f"the loop's {key} per run is {got}, the text's macros say otherwise")

    # ---- the gate test, by kind of candidate --------------------------------------------
    gates = rows("gates.jsonl")
    tier_name = {"always": "always-on skill", "rule": "rule", "rule-always": "rule",
                 "gated": "gated skill"}
    # the caption says one harmful rule has no paths (it loads on every turn), and no other
    if [g["type"] for g in gates if g["screen"]["candidate_tier"] == "rule-always"] != ["harmful"]:
        stop("the path-less rules of the gate test are not one harmful rule")
    order = [("placebo-topic", "placebo, about a topic"), ("placebo-moment", "placebo, about a moment"),
             ("harmful", "harmful"), ("positive", "known-good")]
    body = []
    for t, label in order:
        grp = defaultdict(list)
        for g in gates:
            if g["type"] == t:
                grp[tier_name[g["screen"]["candidate_tier"]]].append(g)
        for tier in ("rule", "gated skill", "always-on skill"):
            gs = grp.get(tier)
            if not gs:
                continue
            fin = lambda g: (g.get("confirm") or {}).get("verdict") or g["screen"]["verdict"]
            opened = sum(1 for g in gs if g["screen"].get("candidate_fired_runs"))
            k = {v: sum(1 for g in gs if fin(g) == v) for v in ("KEEP", "KILL", "RERUN")}
            if sum(k.values()) != len(gs):
                stop(f"a {label} candidate ended with a verdict the table has no column for")
            body.append(rf"{label} & {tier} & {len(gs)} & {opened} & {k['KEEP']} & {k['KILL']} & "
                        rf"{k['RERUN']} & {sum(1 for g in gs if g['verdict'] == 'KILL')} \\")
    tot = defaultdict(int)
    for g in gates:
        tot[(g["type"].split("-")[0], (g.get("confirm") or {}).get("verdict") or g["screen"]["verdict"])] += 1
    if (str(tot[("placebo", "KILL")]), str(tot[("placebo", "RERUN")]), str(tot[("harmful", "KILL")]),
            str(tot[("harmful", "RERUN")])) != (M["GatePlaceboKilled"], M["GatePlaceboUnscored"],
                                                 M["GateHarmfulKilled"], M["GateHarmfulUnscored"]):
        stop("the gate table disagrees with the text's counts")
    write("tab-gates.tex", "\n".join(body) + "\n")

    # ---- the items the loop kept ----------------------------------------------------------
    fam = {(r["run"], r["name"]): r["family"] for r in
           csv.DictReader(open(CORTEX / "lab" / "reports" / "tables" / "T6-items.csv")) if r["fate"] == "kept"}
    rub = {(x["run"], x["name"]): x for x in RB.tier_rubric(d, ev)}
    cc = set.intersection(*[{x["task"] for x in d.bench(runs=[r], split="holdout")} for r in ev])
    body, n_items = [], 0
    for run in ev:
        its = sorted((i for i in d.items if i["run"] == run and i.get("fate") == "kept"),
                     key=lambda i: (fam[(run, i["name"])], i["name"]))
        for i in its:
            f = fam[(run, i["name"])]
            rs = [r for r in d.bench(runs=[run], arms=("evolved",), split="holdout")
                  if r.get("family") == f and r.get("valid", 1) and r["task"] in cc]
            loaded = sum(1 for r in rs if i["name"] in (r.get("fired") or []))
            x = rub[(run, i["name"])]
            scope = ", ".join(tt(p) for p in i["paths"])
            body.append(rf"{run} & {f} & {tt(i['name'])} & {i['kind']} & {scope} & {num(i['chars'])} & "
                        rf"{pct(x['own_rate'])} & {pct(x['other_rate'])} & {x['score']} & "
                        rf"{loaded}/{len(rs)} \\")
            n_items += 1
        if run != ev[-1]:
            body.append(r"\addlinespace")
    if str(n_items) != M["KeptItems"]:
        stop("the kept-items table does not list every kept item")
    write("tab-kept.tex", "\n".join(body) + "\n")

    # ---- what rollouts read that their harness did not give them (Limitations) -----------
    # (the rows are built to check the counts the text quotes; no table is written)
    T = [json.loads(l) for l in (DATA / "transcripts.jsonl").read_text().splitlines() if l.strip()]

    def pick(run, source, arms=None):
        runs_ = tuple(run) if isinstance(run, (tuple, list)) else (run,)
        return [r for r in T if r["run"] in runs_ and r["source"] == source
                and (arms is None or r.get("arm") in arms)]

    def n(rs, *flags):
        return sum(1 for r in rs if set(flags) & set(r["reads"]))
    dash = "--"
    haiku, sonnet = M["RolloutModelName"].replace("Claude ", ""), M["StrongModelName"].replace("Claude ", "")
    lines = [
        # label, model, rollouts, a fix or the lessons, names of items the arm lacks, their text
        (r"the loop's sweeps, R1--R4", haiku, pick(ev, "sweep"), ("fix", "store"), None, None),
        (r"the gate test", haiku, pick("GATE", "sweep"), ("fix", "store"), None, None),
        (r"benchmark, \cmd{none}, R1--R4", haiku, pick(ev, "bench", ("none",)), ("fix", "store"), "names", "text"),
        (r"benchmark, \cmd{none}, D0R", haiku, pick("D0R", "bench", ("none",)), ("fix", "store"), "names", "text"),
        (r"benchmark, \cmd{none2}, \cmd{kitchen}, \cmd{ideal}, R1", haiku,
         pick("R1", "bench", ("none2", "kitchen", "ideal")), ("fix", "store"), "names", "text"),
        (r"benchmark, \cmd{desc-only}, R1", haiku, pick("R1", "bench", ("desc-only",)), ("fix", "store"), None, "text"),
        (r"\cmd{/prune}, removal arm", haiku, pick("PRUNE", "sweep", ("cand",)), ("fix", "store"), "names", "text"),
        (r"benchmark, \cmd{none}", sonnet, pick("M1", "bench", ("none",)), ("fix", "store"), "names", "text"),
        (r"\cmd{/prune}, removal arm", sonnet, pick("M1", "sweep", ("cand",)), ("fix", "store"), "names", "text"),
        (r"\SecondRepo{} benchmark", haiku, pick("X1", "bench"), ("impl",), None, None),
        (r"\SecondRepo{} training sessions", haiku, pick("X1", "session"), ("impl",), None, None),
    ]
    got = {}
    for label, model, rs, fix, names, text in lines:
        got[label + model] = [num(len(rs)), str(n(rs, *fix)), dash if names is None else str(n(rs, names)),
                              dash if text is None else str(n(rs, text))]
    # the text quotes these rows; they must agree
    want = {r"the loop's sweeps, R1--R4" + haiku: (M["LoopSweepRollouts"], M["LoopFixReads"]),
            r"benchmark, \cmd{none}, R1--R4" + haiku: (M["NoneBenchRollouts"], M["NoneBenchFix"],
                                                       M["NoneBenchNames"], M["NoneBenchText"]),
            r"benchmark, \cmd{desc-only}, R1" + haiku: (M["DescBodyRollouts"], "0", dash, M["DescBodySeen"]),
            r"\cmd{/prune}, removal arm" + haiku: (M["PruneRemovalRollouts"], "0", M["PruneRemovalNames"],
                                                  M["PruneRemovalText"]),
            r"benchmark, \cmd{none}" + sonnet: (M["SonnetNoneRollouts"], None, M["SonnetNoneNames"], M["SonnetNoneText"]),
            r"\cmd{/prune}, removal arm" + sonnet: (M["SonnetRemovalRollouts"], None, M["SonnetRemovalNames"],
                                                   M["SonnetRemovalText"]),
            r"\SecondRepo{} benchmark" + haiku: (M["XBenchRollouts"], M["XBenchImpl"]),
            r"\SecondRepo{} training sessions" + haiku: (M["XTrainSessions"], M["XTrainImpl"])}
    for key, vals in want.items():
        if any(v is not None and v != c for v, c in zip(vals, got[key])):
            stop(f"what rollouts read, row '{key}', disagrees with the text: {got[key]} against {vals}")
    if got[r"the gate test" + haiku][1] != "0":
        stop("a gate-test rollout read a fix")


if __name__ == "__main__":
    main()
